"""first

Revision ID: 478fd30a6255
Revises: 
Create Date: 2019-11-18 10:39:17.913490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '478fd30a6255'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('stock_name', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('stock_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stocks')
    # ### end Alembic commands ###
